apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "openshift-jenkins.selectorLabels" . | nindent 4 }}
  name: {{ include "openshift-jenkins.fullname" . }}_edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "openshift-jenkins.serviceAccountName" . }}
