apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
  labels:
    {{- include "openshift-jenkins.labels" . | nindent 4 }}
  name: {{ include "openshift-jenkins.fullname" . }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "openshift-jenkins.fullname" . }}
