FROM openshift/jenkins-slave-base-rhel7

MAINTAINER Ben Parees <bparees@redhat.com>

ENV MAVEN_VERSION=3.0.5

# Install Maven
RUN yum-config-manager --disable epel >/dev/null || : && \
    INSTALL_PKGS="java-1.8.0-openjdk-devel maven" && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y && \
    mkdir -p $HOME/.m2

ADD ./contrib/settings.xml $HOME/.m2/

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
