apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins-agent-base
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    annotations:
      description: Provides a Jenkins Base Agent to extend Jenkins agents
      iconClass: icon-jenkins
      openshift.io/display-name: Jenkins Base Agent
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: jenkins
    from:
      kind: DockerImage
      name: registry.redhat.io/openshift4/ose-jenkins-agent-base:latest
    importPolicy: {}
    referencePolicy:
      type: Local

