#!/bin/bash
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

set -exo nounset
shopt -s nullglob

IMAGE_NAME=${IMAGE_NAME-openshift/jenkins-1-centos7-candidate}

CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
VOLUME=`mktemp -d`
chmod a+rwx $VOLUME

function cleanup() {
  for cidfile in $CIDFILE_DIR/* ; do
    CONTAINER=$(cat $cidfile)

    echo "Stopping and removing container $CONTAINER..."
    docker stop $CONTAINER
    exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
    echo "Dumping logs for $CONTAINER"
    # Dump the logs always (jenkins returns 143 when killed), so we can
    # identify the failures in Jenkins
    [[ "${exit_status}" != "0" ]] && docker logs $CONTAINER
    docker rm $CONTAINER
    rm $cidfile
    echo "Done."
  done
  rmdir $CIDFILE_DIR
  rm -rf $VOLUME
}
trap cleanup EXIT SIGINT

function get_cid() {
  local id="$1" ; shift || return 1
  echo $(cat "$CIDFILE_DIR/$id")
}

function get_container_ip() {
  local id="$1" ; shift
  docker inspect --format='{{.NetworkSettings.IPAddress}}' $(get_cid "$id")
}

test_connection() {
  set +e
  echo "Testing HTTP connection..."
  local max_attempts=10
  local sleep_time=6
  local attempt=1
  local result=1
  while [ $attempt -le $max_attempts ]; do
    echo "Sending GET request to http://${CONTAINER_IP}:8080/"
    response_code=$(curl -s -w %{http_code} -o /dev/null "http://${CONTAINER_IP}:8080/login?from=%2F")
    status=$?
    if [ $status -eq 0 ]; then
      if [ $response_code -eq 200 ]; then
        result=0
        break
      fi
    fi
    attempt=$(( $attempt + 1 ))
    sleep $sleep_time
  done
  set -e
  return $result
}

function create_container() {
  local name=$1 ; shift
  local volume=$1; shift
  local cargs=${CONTAINER_ARGS:-}
  cidfile="$CIDFILE_DIR/$name"
  # create container with a cidfile in a directory for cleanup
  docker run $cargs --name=$name --cidfile $cidfile -d -v $volume:/var/lib/jenkins:Z -p 8080:8080 "$@" $IMAGE_NAME
  echo "Created container $(cat $cidfile)"
}

function delete_container() {
  CONTAINER=$(cat $cidfile)
  docker stop $CONTAINER
  docker rm $CONTAINER
  rm $cidfile  
}

# $1 - username
# $2 - password
# $3 - job name
function test_create_job() {
  curl --fail --user $1:$2 -X POST -H "Content-Type: application/xml" -H "Expect: " --data-binary '@test/testjob.xml' http://${CONTAINER_IP}:8080/createItem\?name=$3
}

# $1 - username
# $2 - password
# $3 - job name
function test_get_job() {
  curl --fail -u $1:$2 -X GET http://${CONTAINER_IP}:8080/job/$3
}

function run_tests() {
  local name=$1 ; shift
  CONTAINER_ARGS="-u 10000:0"
  create_container $name $VOLUME
  CONTAINER_IP=$(get_container_ip $name)
  test_connection $name
  test_create_job admin password testJob
  test_get_job admin password testJob
  set +e
  test_create_job admin badpassword failJob
  if [ $? -eq 0 ]; then
    echo "Fail: was able to create job with bad password"
    return 1
  fi
  set -e

  delete_container

  # start a new container with the old volume so we can try to change the password
  CONTAINER_ARGS="-u 10000:0 -e JENKINS_PASSWORD=newpassword" create_container $name $VOLUME
  CONTAINER_IP=$(get_container_ip $name)

  # need this to wait for the container to start up
  test_connection $name
  # new password should work
  test_get_job admin newpassword testJob
  set +e
  # old password should not
  test_get_job admin password testJob
  if [ $? -eq 0 ]; then
    echo "Fail: was able to get job with bad password"
    return 1
  fi
  set -e
  # Stop the container so next tests can run
  docker stop $(get_cid $name)
  echo "  Success!"
}

function run_s2i_tests() {
  if [ "$(which s2i)" == "" ]; then
    echo "WARNING: Please install the s2i binary to run the s2i tests."
    return
  fi
  output_image="openshift/s2i-test-jenkins"
  s2i build --context-dir="1/test/s2i" --loglevel=3 --pull-policy=never \
    file://$(pwd)/.. $IMAGE_NAME $output_image
  s2i_volume=$(mktemp -d)
  chmod a+rwx $s2i_volume
  IMAGE_NAME="${output_image}" create_container s2i-jenkins-test $s2i_volume
  cid=s2i-jenkins-test
  CONTAINER_IP=$(get_container_ip ${cid})
  test_connection ${cid}
  set +e
  if ! docker exec ${cid} ls /var/lib/jenkins/plugins/sample.jpi.pinned; then
    echo "Fail: The sample.jpi.pinned plugin was not copied"
    return 1
  fi
  if ! docker exec ${cid} ls /var/lib/jenkins/plugins/ansicolor.jpi; then
    echo "Fail: The ansicolor plugin should be installed"
    return 1
  fi
  if ! docker exec ${cid} ls /var/lib/jenkins/jobs/sample-app-test/config.xml; then
    echo "Fail: The sample-app-test job was not copied"
    return 1
  fi
  docker exec ${cid} cat /var/lib/jenkins/config.xml | grep -q "s2i-test-config"
  if [ "$?" != "0" ]; then
    echo "Fail: The config.xml was not copied"
    return 1
  fi
  set -e
  test_get_job admin password sample-app-test
  test_create_job admin password testJob
  test_get_job admin password testJob
}

# Tests.

# Normal tests
run_tests jenkins_test

# S2I tests
run_s2i_tests
