apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/jenkins?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "release-rhel8" && ( "2/***".pathChanged() || ".tekton/***".pathChanged() || ".konflux/rpms-4-13/rpms.lock.yaml".pathChanged() || ".konflux/rpms-4-13/rpms.in.yaml".pathChanged() || ".konflux/ubi.repo".pathChanged() || ".konflux/artifacts.lock.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-jenkins-rhel8
    appstudio.openshift.io/component: jenkins-rhel8-4-12
    pipelines.appstudio.openshift.io/type: build
  name: jenkins-rhel8-4-12-on-push
  namespace: ocp-tools-jenkins-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-tools-jenkins-tenant/jenkins-rhel8-4-12:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: 2/Dockerfile.rhel8
    - name: path-context
      value: "2"
    - name: build-source-image
      value: "true"
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '{"packages": [{"type": "generic", "path": ".konflux"},{"type": "rpm", "path": ".konflux/rpms-4-13"}]}'
    - name: build-args
      value:
        - OCP_VERSION=4.12
        - CI_UPSTREAM_COMMIT={{revision}}
        - CI_UPSTREAM_URL={{source_url}}
        - OC_LEGACY_TAG=v4.12
        - OC_LEGACY_DIR=oc-412
        - OC_VERSION=v4.13
    - name: build-args-file
      value: .konflux/konflux-build-args.env
    - name: LABELS
      value:
        - "io.openshift.release.version=4.12"
        - "version=4.12"
        - "cpe=cpe:/a:redhat:ocp_tools:4.12::el8"
  taskRunTemplate:
    serviceAccountName: build-pipeline-jenkins-rhel8-4-12
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build-pipeline
status: {}
