apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/jenkins?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "release-rhel8" && ( "2/***".pathChanged() || ".tekton/jenkins-rhel8-single-arch-pull-request.yaml".pathChanged() || "2/Dockerfile.rhel8-single-arch".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-jenkins-rhel8
    appstudio.openshift.io/component: jenkins-rhel8-single-arch
    pipelines.appstudio.openshift.io/type: build
  name: jenkins-rhel8-single-arch-on-pull-request
  namespace: ocp-tools-jenkins-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-tools-jenkins-tenant/jenkins-rhel8-single-arch:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: 2/Dockerfile.rhel8-single-arch
    - name: path-context
      value: "2"
    - name: build-source-image
      value: "true"
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '{"packages": [{"type": "generic"},{"type": "rpm"}]}'
  taskRunTemplate:
    serviceAccountName: build-pipeline-jenkins-rhel8-single-arch
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build-pipeline
status: {}
